bugzilla_credentials:
  bugzilla_uri:
  username:
  password:
github_credentials:
  username:
  password:
pivotal_credentials:
  token:

influxdb:
  database_name:
  username:
  password:

commit_monitor:
  bugzilla_product:
diff_content_checker: {}
gem_changes_labeler:
  enabled_repos: []
github_notification_monitor:
  repo_names: []
merge_target_titler:
  enabled_repos: []
pivotal_pr_checker:
  enabled_repos: []
sql_migration_labeler:
  enabled_repos: []
travis_event:
  enabled_repos: []
wip_labeler:
  enabled_repos: []
