# Service credentials
bugzilla_credentials:
  url:
  username:
  password:
github_credentials:
  username:
  password:
influxdb_credentials:
  database:
  username:
  password:
pivotal_credentials:
  token:

# General settings
bugzilla:
  product:
grafana:
  url:

# Worker settings
diff_content_checker:
  offenses: {}
merge_target_titler:
  included_repos: []
path_based_labeler:
  rules: {}
travis_build_killer:
  included_repos: []
