bugzilla_credentials:
  bugzilla_uri:
  username:
  password:
github_credentials:
  username:
  password:
commit_monitor:
  bugzilla_product:
gemfile_checker:
  pr_contacts: []
issue_manager:
  repo_names: []
